version: '3.2'
services:
  postgres-server:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres123dev
      - POSTGRES_USER=postgres
  app:
    build: .
    environment:
      - DATABASE_HOST=postgres-server
      - DATABASE_PASSWORD=postgres123dev
      - DATABASE_USERNAME=postgres
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "3000:3000"
    depends_on:
      - postgres-server
#    command:
     # - ./bin/run.sh
