# This is just an example for purpose of demo! Database should not be deployed like this!
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: example-postgres
  name: example-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: example-postgres
    spec:
      containers:
      - image: postgres
        name: db
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres123
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
