apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: railsk8s-nginx-deploy
  name: railsk8s-nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: railsk8s-ngx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: railsk8s-ngx
    spec:
      containers:
      - image: jakuboboza/rails-on-k8s:ngx_latest
        name: frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "125m"
